### ISSUE TITLE
Push to docker host other than dockerhub?

### ISSUE THREAD

**Issue by mcolyer** [home-assistant/builder#106]
Is it possible to publish containers to the GitHub container registry rather than dockerhub? I looked through the available options and didn't see a way to do this.

**Comment by ludeeus** [comment]
You should be able to do `--docker-hub ghcr.io/username`

**Comment by mcolyer** [comment]
🤦 , sorry for missing that in the docs.

**Comment by ALenfant** [comment]
When attempting to do just that on my machine, I never was able to push anything to `ghcr.io`. If I understand correctly it's because the `docker login` command doesn't work with other repositories since the [CLI argument](https://docs.docker.com/reference/cli/docker/login/#authenticate-to-a-self-hosted-registry) to specify them is [never passed](https://github.com/home-assistant/builder/blob/d88ece7a6d6135dc11eb5ce92cfcd33736d642c5/builder.sh#L982).

Would it be possible to add support for `--docker-hub`/ `DOCKER_HUB` here as well?

Thanks for the help!
